import {
  NULL_VALUE, UNDEFINED_VARIABLE, UNDEFINED_PROPERTY,
  UNDEFINED_VALUE, UNDEFINED_VALUE_MATCH, OUTPUT_MATCH, CALL_MATCH,
  IN_OPERATOR, INVALID_LOOKUP, KEY_NOT_FOUND, NOT_A_FUNCTION,
} from './value-errors.ts';
import {
  UNDEFINED_FUNCTION, UNDEFINED_FILTER, UNDEFINED_TEST,
  UNDEFINED_BLOCK, UNDEFINED_EXTENSION, UNKNOWN_BLOCK_RUNTIME, DUPLICATE_BLOCK, NO_SUPER_BLOCK,
  RESERVED_KEYWORD, RESERVED_KEYWORD_CONTEXT,
} from './reference-errors.ts';
import { TIMEOUT, ASSERT_TYPE_ERROR, UNAVAILABLE_IN_ENV, EXEC_EXPRESSION_ERROR } from './system-errors.ts';

export const RUNTIME_ERRORS = {
  NULL_VALUE,
  UNDEFINED_VARIABLE,
  UNDEFINED_PROPERTY,
  UNDEFINED_VALUE,
  UNDEFINED_VALUE_MATCH,
  OUTPUT_MATCH,
  CALL_MATCH,
  IN_OPERATOR,
  INVALID_LOOKUP,
  KEY_NOT_FOUND,
  NOT_A_FUNCTION,
  UNDEFINED_FUNCTION,
  UNDEFINED_FILTER,
  UNDEFINED_TEST,
  UNDEFINED_BLOCK,
  UNDEFINED_EXTENSION,
  UNKNOWN_BLOCK_RUNTIME,
  DUPLICATE_BLOCK,
  NO_SUPER_BLOCK,
  RESERVED_KEYWORD,
  RESERVED_KEYWORD_CONTEXT,
  TIMEOUT,
  ASSERT_TYPE_ERROR,
  UNAVAILABLE_IN_ENV,
  EXEC_EXPRESSION_ERROR,
} as const;

export type RuntimeErrorName = keyof typeof RUNTIME_ERRORS;
