export const T = Object.freeze({
  NODE: 'node',
  VALUE: 'value',
  LITERAL: 'literal',
  SYMBOL: 'symbol',
  NODE_LIST: 'nodeList',
  OUTPUT: 'output',
  FUN_CALL: 'funCall',
  PIPE: 'pipe',
  BLOCK: 'block',
  EXTENDS: 'extends',
  INCLUDE: 'include',
  COMPONENT: 'component',
  IF: 'if',
  FOR: 'for',
  COMPARE: 'compare',
  LOOKUP_VAL: 'lookupVal',
  CALL_EXTENSION: 'callExtension',
  CALL_EXTENSION_ASYNC: 'callExtensionAsync',
  DICT: 'dict',
  ARRAY: 'array',
  PAIR: 'pair',
  CONCAT: 'concat',
  ADD: 'add',
  SUB: 'sub',
  MUL: 'mul',
  DIV: 'div',
  FLOOR_DIV: 'floorDiv',
  MOD: 'mod',
  POW: 'pow',
  KEYWORD_ARGS: 'keywordArgs',
  ROOT: 'root',
  SLICE: 'slice',
  GROUP: 'group',
  TEMPLATE_DATA: 'templateData',
  INLINE_IF: 'inlineIf',
  OR: 'or',
  AND: 'and',
  NOT: 'not',
  COMPARE_OPERAND: 'compareOperand',
  NEG: 'neg',
  POS: 'pos',
  SUPER: 'super',
  IMPORT: 'import',
  FROM_IMPORT: 'fromImport',
  SWITCH: 'switch',
  CASE: 'case',
  CAPTURE: 'capture',
  OPTIONAL_CHAIN: 'optionalChain',
  OPTIONAL_CALL: 'optionalCall',
  NULLISH_COALESCE: 'nullishCoalesce',
  IN: 'in',
  EXEC: 'exec',
  SCOPE: 'scope',
  IS: 'is',
  SPREAD: 'spread',
  WALRUS: 'walrus',
  TEMPLATE_LITERAL: 'templateLiteral',
  VARIABLE_DECLARATION: 'variableDeclaration',
  VARIABLE_ASSIGNMENT: 'variableAssignment',
  COMPOUND_ASSIGNMENT: 'compoundAssignment',
  BITWISE_OR: 'bitwiseOr',
  BITWISE_AND: 'bitwiseAnd',
  BITWISE_XOR: 'bitwiseXor',
  BITWISE_LSHIFT: 'bitwiseLShift',
  BITWISE_RSHIFT: 'bitwiseRShift',
  BITWISE_NOT: 'bitwiseNot',
  INCREMENT: 'increment',
  DECREMENT: 'decrement',
  ARRAY_PATTERN: 'arrayPattern',
  OBJECT_PATTERN: 'objectPattern',
  PATTERN_PROPERTY: 'patternProperty',
  REST_PATTERN: 'restPattern',
  ASSIGNMENT_PATTERN: 'assignmentPattern',
  HOLE: 'hole',
  TEST: 'test',
  TEST_CALL: 'testCall',
  MATCH: 'match',
  WHEN: 'when',
  RANGE: 'range',
  RENDER: 'render',
} as const);

export type NodeType = typeof T[keyof typeof T];

export const BracketNotation = Symbol('BracketNotation');

export const FIELDS: Readonly<Record<NodeType, readonly string[]>> = {
  [T.NODE]: [],
  [T.VALUE]: ['value'],
  [T.LITERAL]: ['value'],
  [T.SYMBOL]: ['value'],
  [T.TEMPLATE_DATA]: ['value'],
  [T.NODE_LIST]: ['children'],
  [T.OUTPUT]: ['children'],
  [T.ROOT]: ['children'],
  [T.GROUP]: ['children'],
  [T.ARRAY]: ['children'],
  [T.DICT]: ['children'],
  [T.ARRAY_PATTERN]: ['children'],
  [T.OBJECT_PATTERN]: ['children'],
  [T.KEYWORD_ARGS]: ['children'],
  [T.FUN_CALL]: ['name', 'args'],
  [T.PIPE]: ['name', 'args'],
  [T.OPTIONAL_CALL]: ['name', 'args'],
  [T.LOOKUP_VAL]: ['target', 'val'],
  [T.OPTIONAL_CHAIN]: ['target', 'val'],
  [T.SLICE]: ['start', 'stop', 'step'],
  [T.ADD]: ['left', 'right', 'operator'],
  [T.SUB]: ['left', 'right', 'operator'],
  [T.MUL]: ['left', 'right', 'operator'],
  [T.DIV]: ['left', 'right', 'operator'],
  [T.FLOOR_DIV]: ['left', 'right', 'operator'],
  [T.MOD]: ['left', 'right', 'operator'],
  [T.POW]: ['left', 'right', 'operator'],
  [T.CONCAT]: ['left', 'right'],
  [T.AND]: ['left', 'right'],
  [T.OR]: ['left', 'right'],
  [T.NOT]: ['target', 'operator'],
  [T.NEG]: ['target', 'operator'],
  [T.POS]: ['target', 'operator'],
  [T.COMPARE]: ['expr', 'ops'],
  [T.COMPARE_OPERAND]: ['expr', 'operator'],
  [T.NULLISH_COALESCE]: ['left', 'right'],
  [T.IN]: ['left', 'right'],
  [T.IS]: ['left', 'right'],
  [T.BITWISE_OR]: ['left', 'right'],
  [T.BITWISE_AND]: ['left', 'right'],
  [T.BITWISE_XOR]: ['left', 'right'],
  [T.BITWISE_LSHIFT]: ['left', 'right'],
  [T.BITWISE_RSHIFT]: ['left', 'right'],
  [T.BITWISE_NOT]: ['target'],
  [T.INCREMENT]: ['target', 'isPostfix'],
  [T.DECREMENT]: ['target', 'isPostfix'],
  [T.BLOCK]: ['name', 'body'],
  [T.EXTENDS]: ['template'],
  [T.INCLUDE]: ['template', 'ignoreMissing'],
  [T.COMPONENT]: ['name', 'args', 'body', 'fallbackSlots'],
  [T.IMPORT]: ['template', 'target', 'withContext'],
  [T.FROM_IMPORT]: ['template', 'names', 'withContext'],
  [T.IF]: ['cond', 'body', 'else_'],
  [T.INLINE_IF]: ['cond', 'body', 'else_'],
  [T.FOR]: ['arr', 'name', 'body', 'else_'],
  [T.SWITCH]: ['expr', 'cases', 'default'],
  [T.CASE]: ['cond', 'body'],
  [T.CAPTURE]: ['body', 'name'],
  [T.EXEC]: ['expr'],
  [T.SCOPE]: ['assignments', 'body'],
  [T.SUPER]: ['blockName', 'symbol'],
  [T.SPREAD]: ['argument'],
  [T.WALRUS]: ['target', 'value'],
  [T.TEMPLATE_LITERAL]: ['quasis'],
  [T.VARIABLE_DECLARATION]: ['targets', 'value'],
  [T.VARIABLE_ASSIGNMENT]: ['targets', 'value'],
  [T.COMPOUND_ASSIGNMENT]: ['targets', 'operator', 'value'],
  [T.PATTERN_PROPERTY]: ['key', 'value'],
  [T.REST_PATTERN]: ['target'],
  [T.ASSIGNMENT_PATTERN]: ['target', 'value'],
  [T.PAIR]: ['key', 'value'],
  [T.HOLE]: [],
  [T.CALL_EXTENSION]: ['extName', 'prop', 'args', 'contentArgs', 'autoescape'],
  [T.CALL_EXTENSION_ASYNC]: ['extName', 'prop', 'args', 'contentArgs', 'autoescape'],
  [T.TEST]: ['target', 'name'],
  [T.TEST_CALL]: ['target', 'name', 'args'],
  [T.MATCH]: ['expr', 'cases', 'default'],
  [T.WHEN]: ['pattern', 'guard', 'body'],
  [T.RANGE]: ['left', 'right'],
  [T.RENDER]: ['callExpr', 'body', 'providedSlots'],
};
