export type { NodeType } from './constants.ts';
export { BracketNotation, T } from './constants.ts';
// WHY: curated barrel — guards and node-type names are listed explicitly so a new export
// cannot silently widen the nodes public API; adding a name requires an edit here.
export {
  isArray,
  isArrayPattern,
  isAssignmentPattern,
  isBlock,
  isCallExtension,
  isCallExtensionAsync,
  isChildrenNode,
  isCompareOperand,
  isDict,
  isFunCall,
  isHole,
  isIf,
  isKeywordArgs,
  isLiteral,
  isLookupVal,
  isNode,
  isNodeList,
  isObjectPattern,
  isOptionalCall,
  isOptionalChain,
  isPair,
  isPatternProperty,
  isPipe,
  isRestPattern,
  isSlice,
  isSpread,
  isSymbol,
  isTemplateData,
  isVariableAssignment,
  isVariableDeclaration,
} from './guards.ts';
export { FIELDS } from './node-fields.ts';
export type {
  AssignmentPatternNode,
  BinaryNode,
  BinaryOpNode,
  BlockNode,
  CallExtensionNode,
  CallNode,
  CaptureNode,
  CaseNode,
  ChildrenNode,
  CompareNode,
  CompareOperandNode,
  ComponentNode,
  CompoundAssignNode,
  ExecNode,
  ExtendsNode,
  ForNode,
  FromImportNode,
  HoleNode,
  IfNode,
  ImportNode,
  IncDecNode,
  IncludeNode,
  LiteralNode,
  LookupNode,
  MatchNode,
  Node,
  NodeBase,
  NodeLocation,
  NodeOf,
  PairNode,
  RangeNode,
  RenderNode,
  RestPatternNode,
  ScopeNode,
  SliceNode,
  SlotBlock,
  SpreadNode,
  SuperNode,
  SwitchNode,
  SymbolNode,
  TemplateDataNode,
  TemplateLiteralNode,
  TemplateQuasi,
  TestCallNode,
  TestNode,
  UnaryNode,
  UnaryOpNode,
  VariableDeclNode,
  WalrusNode,
  WhenNode,
} from './node-types.ts';
