import { type NodeType, T } from './constants.ts';

// WHY: each FIELDS array is shared by reference into every node of its type
// (create-node.ts embeds it directly) — frozen at declaration so a stray
// mutation anywhere fails loudly instead of silently corrupting all nodes
// of that type process-wide.
const frozen = (fields: string[]): readonly string[] => Object.freeze(fields);

export const FIELDS: Readonly<Record<NodeType, readonly string[]>> = {
  [T.LITERAL]: frozen(['value']),
  [T.SYMBOL]: frozen(['value']),
  [T.TEMPLATE_DATA]: frozen(['value']),
  [T.NODE_LIST]: frozen(['children']),
  [T.OUTPUT]: frozen(['children']),
  [T.ROOT]: frozen(['children']),
  [T.GROUP]: frozen(['children']),
  [T.ARRAY]: frozen(['children']),
  [T.DICT]: frozen(['children']),
  [T.ARRAY_PATTERN]: frozen(['children']),
  [T.OBJECT_PATTERN]: frozen(['children']),
  [T.KEYWORD_ARGS]: frozen(['children']),
  [T.FUN_CALL]: frozen(['name', 'args']),
  [T.PIPE]: frozen(['name', 'args']),
  [T.OPTIONAL_CALL]: frozen(['name', 'args']),
  [T.LOOKUP_VAL]: frozen(['target', 'val']),
  [T.OPTIONAL_CHAIN]: frozen(['target', 'val']),
  [T.SLICE]: frozen(['start', 'stop', 'step']),
  [T.ADD]: frozen(['left', 'right', 'operator']),
  [T.SUB]: frozen(['left', 'right', 'operator']),
  [T.MUL]: frozen(['left', 'right', 'operator']),
  [T.DIV]: frozen(['left', 'right', 'operator']),
  [T.FLOOR_DIV]: frozen(['left', 'right', 'operator']),
  [T.MOD]: frozen(['left', 'right', 'operator']),
  [T.POW]: frozen(['left', 'right', 'operator']),
  [T.CONCAT]: frozen(['left', 'right']),
  [T.AND]: frozen(['left', 'right']),
  [T.OR]: frozen(['left', 'right']),
  [T.NOT]: frozen(['target', 'operator']),
  [T.NEG]: frozen(['target', 'operator']),
  [T.POS]: frozen(['target', 'operator']),
  [T.COMPARE]: frozen(['expr', 'ops']),
  [T.COMPARE_OPERAND]: frozen(['expr', 'operator']),
  [T.NULLISH_COALESCE]: frozen(['left', 'right']),
  [T.IN]: frozen(['left', 'right']),
  [T.IS]: frozen(['left', 'right']),
  [T.BITWISE_OR]: frozen(['left', 'right']),
  [T.BITWISE_AND]: frozen(['left', 'right']),
  [T.BITWISE_XOR]: frozen(['left', 'right']),
  [T.BITWISE_LSHIFT]: frozen(['left', 'right']),
  [T.BITWISE_RSHIFT]: frozen(['left', 'right']),
  [T.BITWISE_NOT]: frozen(['target']),
  [T.INCREMENT]: frozen(['target', 'isPostfix']),
  [T.DECREMENT]: frozen(['target', 'isPostfix']),
  [T.BLOCK]: frozen(['name', 'body']),
  [T.EXTENDS]: frozen(['template']),
  [T.INCLUDE]: frozen(['template', 'ignoreMissing', 'only', 'with']),
  [T.COMPONENT]: frozen(['name', 'args', 'body', 'fallbackSlots']),
  [T.IMPORT]: frozen(['template', 'target', 'withContext']),
  [T.FROM_IMPORT]: frozen(['template', 'names', 'withContext']),
  [T.IF]: frozen(['cond', 'body', 'alternate']),
  [T.INLINE_IF]: frozen(['cond', 'body', 'alternate']),
  [T.FOR]: frozen(['arr', 'name', 'body', 'alternate']),
  [T.SWITCH]: frozen(['expr', 'cases', 'default']),
  [T.CASE]: frozen(['cond', 'body']),
  [T.CAPTURE]: frozen(['body', 'name']),
  [T.EXEC]: frozen(['expr']),
  [T.SCOPE]: frozen(['assignments', 'body']),
  [T.SUPER]: frozen(['blockName', 'symbol']),
  [T.SPREAD]: frozen(['argument']),
  [T.WALRUS]: frozen(['target', 'value']),
  [T.TEMPLATE_LITERAL]: frozen(['quasis']),
  [T.VARIABLE_DECLARATION]: frozen(['targets', 'value']),
  [T.VARIABLE_ASSIGNMENT]: frozen(['targets', 'value']),
  [T.COMPOUND_ASSIGNMENT]: frozen(['targets', 'operator', 'value']),
  [T.PATTERN_PROPERTY]: frozen(['key', 'value']),
  [T.REST_PATTERN]: frozen(['target']),
  [T.ASSIGNMENT_PATTERN]: frozen(['target', 'value']),
  [T.PAIR]: frozen(['key', 'value']),
  [T.HOLE]: frozen([]),
  [T.CALL_EXTENSION]: frozen(['extName', 'prop', 'args', 'contentArgs', 'autoescape']),
  [T.CALL_EXTENSION_ASYNC]: frozen(['extName', 'prop', 'args', 'contentArgs', 'autoescape']),
  [T.TEST]: frozen(['target', 'name']),
  [T.TEST_CALL]: frozen(['target', 'name', 'args']),
  [T.MATCH]: frozen(['expr', 'cases', 'default']),
  [T.WHEN]: frozen(['pattern', 'guard', 'body']),
  [T.RANGE]: frozen(['left', 'right']),
  [T.RENDER]: frozen(['callExpr', 'body', 'providedSlots']),
};
