import { type NodeType, T } from './constants.ts';

export const FIELDS: Readonly<Record<NodeType, readonly string[]>> = {
  [T.LITERAL]: ['value'],
  [T.SYMBOL]: ['value'],
  [T.TEMPLATE_DATA]: ['value'],
  [T.NODE_LIST]: ['children'],
  [T.OUTPUT]: ['children'],
  [T.ROOT]: ['children'],
  [T.GROUP]: ['children'],
  [T.ARRAY]: ['children'],
  [T.DICT]: ['children'],
  [T.ARRAY_PATTERN]: ['children'],
  [T.OBJECT_PATTERN]: ['children'],
  [T.KEYWORD_ARGS]: ['children'],
  [T.FUN_CALL]: ['name', 'args'],
  [T.PIPE]: ['name', 'args'],
  [T.OPTIONAL_CALL]: ['name', 'args'],
  [T.LOOKUP_VAL]: ['target', 'val'],
  [T.OPTIONAL_CHAIN]: ['target', 'val'],
  [T.SLICE]: ['start', 'stop', 'step'],
  [T.ADD]: ['left', 'right', 'operator'],
  [T.SUB]: ['left', 'right', 'operator'],
  [T.MUL]: ['left', 'right', 'operator'],
  [T.DIV]: ['left', 'right', 'operator'],
  [T.FLOOR_DIV]: ['left', 'right', 'operator'],
  [T.MOD]: ['left', 'right', 'operator'],
  [T.POW]: ['left', 'right', 'operator'],
  [T.CONCAT]: ['left', 'right'],
  [T.AND]: ['left', 'right'],
  [T.OR]: ['left', 'right'],
  [T.NOT]: ['target', 'operator'],
  [T.NEG]: ['target', 'operator'],
  [T.POS]: ['target', 'operator'],
  [T.COMPARE]: ['expr', 'ops'],
  [T.COMPARE_OPERAND]: ['expr', 'operator'],
  [T.NULLISH_COALESCE]: ['left', 'right'],
  [T.IN]: ['left', 'right'],
  [T.IS]: ['left', 'right'],
  [T.BITWISE_OR]: ['left', 'right'],
  [T.BITWISE_AND]: ['left', 'right'],
  [T.BITWISE_XOR]: ['left', 'right'],
  [T.BITWISE_LSHIFT]: ['left', 'right'],
  [T.BITWISE_RSHIFT]: ['left', 'right'],
  [T.BITWISE_NOT]: ['target'],
  [T.INCREMENT]: ['target', 'isPostfix'],
  [T.DECREMENT]: ['target', 'isPostfix'],
  [T.BLOCK]: ['name', 'body'],
  [T.EXTENDS]: ['template'],
  [T.INCLUDE]: ['template', 'ignoreMissing', 'only', 'with'],
  [T.COMPONENT]: ['name', 'args', 'body', 'fallbackSlots'],
  [T.IMPORT]: ['template', 'target', 'withContext'],
  [T.FROM_IMPORT]: ['template', 'names', 'withContext'],
  [T.IF]: ['cond', 'body', 'alternate'],
  [T.INLINE_IF]: ['cond', 'body', 'alternate'],
  [T.FOR]: ['arr', 'name', 'body', 'alternate'],
  [T.SWITCH]: ['expr', 'cases', 'default'],
  [T.CASE]: ['cond', 'body'],
  [T.CAPTURE]: ['body', 'name'],
  [T.EXEC]: ['expr'],
  [T.SCOPE]: ['assignments', 'body'],
  [T.SUPER]: ['blockName', 'symbol'],
  [T.SPREAD]: ['argument'],
  [T.WALRUS]: ['target', 'value'],
  [T.TEMPLATE_LITERAL]: ['quasis'],
  [T.VARIABLE_DECLARATION]: ['targets', 'value'],
  [T.VARIABLE_ASSIGNMENT]: ['targets', 'value'],
  [T.COMPOUND_ASSIGNMENT]: ['targets', 'operator', 'value'],
  [T.PATTERN_PROPERTY]: ['key', 'value'],
  [T.REST_PATTERN]: ['target'],
  [T.ASSIGNMENT_PATTERN]: ['target', 'value'],
  [T.PAIR]: ['key', 'value'],
  [T.HOLE]: [],
  [T.CALL_EXTENSION]: ['extName', 'prop', 'args', 'contentArgs', 'autoescape'],
  [T.CALL_EXTENSION_ASYNC]: ['extName', 'prop', 'args', 'contentArgs', 'autoescape'],
  [T.TEST]: ['target', 'name'],
  [T.TEST_CALL]: ['target', 'name', 'args'],
  [T.MATCH]: ['expr', 'cases', 'default'],
  [T.WHEN]: ['pattern', 'guard', 'body'],
  [T.RANGE]: ['left', 'right'],
  [T.RENDER]: ['callExpr', 'body', 'providedSlots'],
};

// WHY: each FIELDS array is shared by reference into every node of its type
// (create-node.ts embeds it directly) — freezing them once at module init makes a stray
// mutation anywhere fail loudly instead of silently corrupting all nodes of that type
// process-wide.
Object.values(FIELDS).forEach((fields) => {
  Object.freeze(fields);
});
