// WHY: pure re-export barrel for the node factories — the line count is a formatting artifact of
// biome's multiline export expansion, not decomposable logic.
// biome-ignore lint/style/noExcessiveLinesPerFile: re-export barrel only
import * as traverse from '../traverse.ts';
import * as guards from '../types/guards.ts';
import {
  array,
  dict,
  group,
  hole,
  keywordArgs,
  literal,
  nodeList,
  output,
  pair,
  range,
  root,
  spread,
  symbol,
  templateData,
  templateLiteral,
  walrus,
} from './atomic.ts';
import {
  block,
  callExtension,
  callExtensionAsync,
  capture,
  caseNode,
  component,
  execNode,
  extendsNode,
  forNode,
  fromImportNode,
  ifNode,
  importNode,
  include,
  inlineIf,
  match,
  renderNode,
  scopeNode,
  superNode,
  switchNode,
  when,
} from './control.ts';
import { createNode, T } from './create-node.ts';
import {
  add,
  and,
  arrayPattern,
  assignmentPattern,
  bitwiseAnd,
  bitwiseLShift,
  bitwiseNot,
  bitwiseOr,
  bitwiseRShift,
  bitwiseXor,
  compare,
  compareOperand,
  compoundAssignment,
  concat,
  decrement,
  div,
  floorDiv,
  funCall,
  increment,
  inNode,
  isOp,
  lookupVal,
  mod,
  mul,
  neg,
  not,
  nullishCoalesce,
  objectPattern,
  optionalCall,
  optionalChain,
  or,
  patternProperty,
  pipe,
  pos,
  pow,
  restPattern,
  slice,
  sub,
  testCallNode,
  testNode,
  variableAssignment,
  variableDeclaration,
} from './operations.ts';

export { createNode };

const nodes = Object.freeze({
  NODE_TYPES: T,
  nodeList,
  output,
  root,
  literal,
  symbol,
  templateData,
  funCall,
  pipe,
  lookupVal,
  slice,
  optionalChain,
  optionalCall,
  add,
  sub,
  mul,
  div,
  floorDiv,
  mod,
  pow,
  concat,
  not,
  neg,
  pos,
  and,
  or,
  nullishCoalesce,
  compare,
  compareOperand,
  bitwiseOr,
  bitwiseAnd,
  bitwiseXor,
  bitwiseLShift,
  bitwiseRShift,
  bitwiseNot,
  increment,
  decrement,
  is: isOp,
  in: inNode,
  for: forNode,
  inlineIf,
  if: ifNode,
  block,
  capture,
  exec: execNode,
  scope: scopeNode,
  switch: switchNode,
  case: caseNode,
  extends: extendsNode,
  include,
  super: superNode,
  group,
  array,
  dict,
  pair,
  spread,
  walrus,
  templateLiteral,
  keywordArgs,
  variableDeclaration,
  variableAssignment,
  compoundAssignment,
  callExtension,
  callExtensionAsync,
  test: testNode,
  testCall: testCallNode,
  arrayPattern,
  objectPattern,
  patternProperty,
  restPattern,
  assignmentPattern,
  hole,
  ...guards,
  ...traverse,
  createNode,
});

export {
  add,
  and,
  array,
  arrayPattern,
  assignmentPattern,
  bitwiseAnd,
  bitwiseLShift,
  bitwiseNot,
  bitwiseOr,
  bitwiseRShift,
  bitwiseXor,
  block,
  callExtension,
  callExtensionAsync,
  capture,
  caseNode,
  compare,
  compareOperand,
  component,
  compoundAssignment,
  concat,
  decrement,
  dict,
  div,
  execNode,
  extendsNode,
  floorDiv,
  forNode,
  fromImportNode,
  funCall,
  group,
  hole,
  ifNode,
  importNode,
  include,
  increment,
  inlineIf,
  inNode,
  isOp,
  keywordArgs,
  literal,
  lookupVal,
  match,
  mod,
  mul,
  neg,
  nodeList,
  nodes,
  not,
  nullishCoalesce,
  objectPattern,
  optionalCall,
  optionalChain,
  or,
  output,
  pair,
  patternProperty,
  pipe,
  pos,
  pow,
  range,
  renderNode,
  restPattern,
  root,
  scopeNode,
  slice,
  spread,
  sub,
  superNode,
  switchNode,
  symbol,
  templateData,
  templateLiteral,
  testCallNode,
  testNode,
  variableAssignment,
  variableDeclaration,
  walrus,
  when,
};

import type { PairFields, SpreadFields, WalrusFields } from './atomic.ts';
import type {
  BlockFields,
  CallExtensionFields,
  CaptureFields,
  CaseFields,
  ComponentFields,
  ForFields,
  FromImportFields,
  ImportFields,
  IncludeFields,
  InlineIfFields,
  MatchFields,
  RenderFields,
  ScopeFields,
  SuperFields,
  SwitchFields,
  WhenFields,
} from './control.ts';
import type {
  AssignmentPatternFields,
  BinaryFields,
  CallFields,
  CompareFields,
  CompareOperandFields,
  CompoundAssignmentFields,
  IncDecFields,
  LookupFields,
  PatternPropertyFields,
  SliceFields,
  TestCallFields,
  TestNodeFields,
  VariableDeclFields,
} from './operations.ts';

export type {
  AssignmentPatternFields,
  BinaryFields,
  BlockFields,
  CallExtensionFields,
  CallFields,
  CaptureFields,
  CaseFields,
  CompareFields,
  CompareOperandFields,
  ComponentFields,
  CompoundAssignmentFields,
  ForFields,
  FromImportFields,
  ImportFields,
  IncDecFields,
  IncludeFields,
  InlineIfFields,
  LookupFields,
  MatchFields,
  PairFields,
  PatternPropertyFields,
  RenderFields,
  ScopeFields,
  SliceFields,
  SpreadFields,
  SuperFields,
  SwitchFields,
  TestCallFields,
  TestNodeFields,
  VariableDeclFields,
  WalrusFields,
  WhenFields,
};
