import { describe, test, expect } from 'bun:test';
import * as mod from './index.js';

describe('lexer/index exports', () => {
  test('exports Tokenizer', () => expect(mod.Tokenizer).toBeFunction());
  test('exports lex', () => expect(mod.lex).toBeFunction());
  test('exports createToken', () => expect(mod.createToken).toBeFunction());
  test('exports TOKEN_BLOCK_END', () => expect(mod.TOKEN_BLOCK_END).toBe('block-end'));
  test('exports TOKEN_BLOCK_START', () => expect(mod.TOKEN_BLOCK_START).toBeString());
  test('exports TOKEN_SYMBOL', () => expect(mod.TOKEN_SYMBOL).toBe('symbol'));
  test('exports TOKEN_DATA', () => expect(mod.TOKEN_DATA).toBe('data'));
  test('exports TOKEN_STRING', () => expect(mod.TOKEN_STRING).toBe('string'));
  test('exports TOKEN_INT', () => expect(mod.TOKEN_INT).toBe('int'));
  test('exports TOKEN_FLOAT', () => expect(mod.TOKEN_FLOAT).toBe('float'));
  test('exports TOKEN_BOOLEAN', () => expect(mod.TOKEN_BOOLEAN).toBe('boolean'));
  test('exports TOKEN_NONE', () => expect(mod.TOKEN_NONE).toBe('none'));
  test('exports TOKEN_TYPES', () => expect(mod.TOKEN_TYPES).toBeObject());
  test('exports TOKEN_VARIABLE_START', () => expect(mod.TOKEN_VARIABLE_START).toBeString());
  test('exports TOKEN_VARIABLE_END', () => expect(mod.TOKEN_VARIABLE_END).toBeString());
  test('exports TOKEN_COMMENT', () => expect(mod.TOKEN_COMMENT).toBe('comment'));
  test('exports TOKEN_OPERATOR', () => expect(mod.TOKEN_OPERATOR).toBe('operator'));
  test('exports TOKEN_PIPEFORWARD', () => expect(mod.TOKEN_PIPEFORWARD).toBe('pipe-forward'));
  test('exports TOKEN_LEFT_PAREN', () => expect(mod.TOKEN_LEFT_PAREN).toBe('left-paren'));
  test('exports TOKEN_RIGHT_PAREN', () => expect(mod.TOKEN_RIGHT_PAREN).toBe('right-paren'));
  test('exports TOKEN_LEFT_BRACKET', () => expect(mod.TOKEN_LEFT_BRACKET).toBe('left-bracket'));
  test('exports TOKEN_RIGHT_BRACKET', () => expect(mod.TOKEN_RIGHT_BRACKET).toBe('right-bracket'));
  test('exports TOKEN_LEFT_CURLY', () => expect(mod.TOKEN_LEFT_CURLY).toBe('left-curly'));
  test('exports TOKEN_RIGHT_CURLY', () => expect(mod.TOKEN_RIGHT_CURLY).toBe('right-curly'));
  test('exports TOKEN_COMMA', () => expect(mod.TOKEN_COMMA).toBe('comma'));
  test('exports TOKEN_COLON', () => expect(mod.TOKEN_COLON).toBe('colon'));
  test('exports TOKEN_TILDE', () => expect(mod.TOKEN_TILDE).toBe('tilde'));
  test('exports TOKEN_WHITESPACE', () => expect(mod.TOKEN_WHITESPACE).toBe('whitespace'));
  test('exports TOKEN_SPECIAL', () => expect(mod.TOKEN_SPECIAL).toBe('special'));
  test('exports TOKEN_REGEX', () => expect(mod.TOKEN_REGEX).toBe('regex'));
  test('exports COMPLEX_OPERATORS', () => expect(mod.COMPLEX_OPERATORS).toBeObject());
  test('exports createDelimiters', () => expect(mod.createDelimiters).toBeFunction());
  test('exports DEFAULT_BLOCK_END', () => expect(mod.DEFAULT_BLOCK_END).toBeString());
  test('exports DEFAULT_BLOCK_START', () => expect(mod.DEFAULT_BLOCK_START).toBeString());
  test('exports DEFAULT_COMMENT_END', () => expect(mod.DEFAULT_COMMENT_END).toBeString());
  test('exports DEFAULT_COMMENT_START', () => expect(mod.DEFAULT_COMMENT_START).toBeString());
  test('exports DEFAULT_VARIABLE_END', () => expect(mod.DEFAULT_VARIABLE_END).toBeString());
  test('exports DEFAULT_VARIABLE_START', () => expect(mod.DEFAULT_VARIABLE_START).toBeString());
  test('exports DELIM_CHARS', () => expect(mod.DELIM_CHARS).toBeString());
  test('exports INT_CHARS', () => expect(mod.INT_CHARS).toBeString());
  test('exports REGEX_FLAGS', () => expect(mod.REGEX_FLAGS).toBeArray());
  test('exports WHITESPACE_CHARS', () => expect(mod.WHITESPACE_CHARS).toBeString());
});
