// TYPES - Core type definitions and constants
// Import directly: import { T, Node } from '@nunjucks/nodes/types'

export type NodeType = string;

export interface Node {
  readonly type: NodeType;
  readonly lineno: number;
  readonly colno: number;
  fields?: readonly string[];
  children?: Node[];
  body?: Node | null;
  [key: string]: unknown;
}

export const T = Object.freeze({
  NODE: 'node',
  VALUE: 'value',
  LITERAL: 'literal',
  SYMBOL: 'symbol',
  NODE_LIST: 'nodeList',
  OUTPUT: 'output',
  FUN_CALL: 'funCall',
  PIPE: 'pipe',
  FILTER: 'filter',
  BLOCK: 'block',
  EXTENDS: 'extends',
  INCLUDE: 'include',
  MACRO: 'macro',
  SET: 'set',
  IF: 'if',
  FOR: 'for',
  COMPARE: 'compare',
  LOOKUP_VAL: 'lookupVal',
  CALL_EXTENSION: 'callExtension',
  CALL_EXTENSION_ASYNC: 'callExtensionAsync',
  DICT: 'dict',
  ARRAY: 'array',
  PAIR: 'pair',
  CONCAT: 'concat',
  ADD: 'add',
  SUB: 'sub',
  MUL: 'mul',
  DIV: 'div',
  FLOOR_DIV: 'floorDiv',
  MOD: 'mod',
  POW: 'pow',
  BIN_OP: 'binOp',
  UNARY_OP: 'unaryOp',
  KEYWORD_ARGS: 'keywordArgs',
  ROOT: 'root',
  SLICE: 'slice',
  GROUP: 'group',
  TEMPLATE_DATA: 'templateData',
  INLINE_IF: 'inlineIf',
  OR: 'or',
  AND: 'and',
  NOT: 'not',
  COMPARE_OPERAND: 'compareOperand',
  NEG: 'neg',
  POS: 'pos',
  SUPER: 'super',
  TEMPLATE_REF: 'templateRef',
  IMPORT: 'import',
  FROM_IMPORT: 'fromImport',
  SWITCH: 'switch',
  CASE: 'case',
  CAPTURE: 'capture',
  CALLER: 'caller',
  CALL: 'call',
  OPTIONAL_CHAIN: 'optionalChain',
  OPTIONAL_CALL: 'optionalCall',
  PIPE_ASYNC: 'pipeAsync',
  NULLISH_COALESCE: 'nullishCoalesce',
  IN: 'in',
  TRY_CATCH: 'tryCatch',
  DO: 'do',
  WITH: 'with',
  IS: 'is',
  SPREAD: 'spread',
  WALRUS: 'walrus',
  TEMPLATE_LITERAL: 'templateLiteral',
  VARIABLE_DECLARATION: 'variableDeclaration',
  VARIABLE_ASSIGNMENT: 'variableAssignment',
  COMPOUND_ASSIGNMENT: 'compoundAssignment',
  DEFINE_BLOCK: 'defineBlock',
  BITWISE_OR: 'bitwiseOr',
  BITWISE_AND: 'bitwiseAnd',
  BITWISE_XOR: 'bitwiseXor',
  BITWISE_LSHIFT: 'bitwiseLShift',
  BITWISE_RSHIFT: 'bitwiseRShift',
  BITWISE_NOT: 'bitwiseNot',
  INCREMENT: 'increment',
  DECREMENT: 'decrement',
  ARRAY_PATTERN: 'arrayPattern',
  OBJECT_PATTERN: 'objectPattern',
  PATTERN_PROPERTY: 'patternProperty',
  REST_PATTERN: 'restPattern',
  ASSIGNMENT_PATTERN: 'assignmentPattern',
  HOLE: 'hole',
} as const);

export const BracketNotation = Symbol('BracketNotation');
