export const PATTERNS = {
  UNDEFINED_VARIABLE: /attempted to output null or undefined value/i,
  UNDEFINED_FUNCTION: /Unable to call `([^`]+)`.*which is undefined/i,
  NOT_A_FUNCTION: /is not a function|is not defined/i,
  SYNTAX_ERROR: /Unexpected token|unexpected end|SyntaxError/i,
  UNDEFINED_FILTER: /filter.*not found|invalid filter/i,
  UNDEFINED_BLOCK: /block.*not found|undefined block/i,
  LINE_INFO: /\[Line (\d+)(?:, Column (\d+))?\]/i,
  INCLUDED_FROM: /\(included from ([^:)]+\.html)(?::\d+)?(?::\d+)?\)/,
  INCLUDED_FROM_WITH_LINE: /\(included from ([^:]+\.html):(\d+)(?::(\d+))?\)/,
  COLUMN_INFO: /Column (\d+)/i,
  ERROR_PREFIX: /^  Error:/i,
  CALL_MATCH: /Unable to call `([^`]+)`/,
  OUTPUT_MATCH: /attempted to output ([^ ]+)/i,
  FILTER_NOT_FOUND: /filter "([^"]+)" not found/i,
};
