export const PATTERNS = {
  UNDEFINED_VARIABLE: /attempted to output '([^']+)' null or undefined/i,
  UNDEFINED_VALUE: /attempted to output null or undefined value/i,
  UNDEFINED_FUNCTION: /Unable to call `([^`]+)`.*which is (?:undefined|null|falsey)/i,
  NOT_A_FUNCTION: /is not a function|is not defined/i,
  SYNTAX_ERROR: /unexpected token|expected (?:comma|variable end|end)|parse[A-Z]|SyntaxError/i,
  UNDEFINED_FILTER: /filter not found: (\w+)/i,
  UNDEFINED_BLOCK: /block.*not found|undefined block/i,
  NO_SUPER_BLOCK: /no super block available/i,
  CIRCULAR_INCLUDE: /Circular include detected/i,
  FILE_NOT_FOUND: /template not found: (.+)/i,
  INVALID_INCLUDE: /template names must be a string/i,
  FILESYSTEM_ERROR: /EISDIR|ENOENT|permission denied/i,
  FILTER_ERROR: /^Error: (.+)/i,
  LINE_INFO: /\[Line (\d+)(?:, Column (\d+))?\]/i,
  INCLUDED_FROM: /\(included from ([^:)]+\.html)(?::\d+)?(?::\d+)?\)/,
  INCLUDED_FROM_WITH_LINE: /\(included from ([^:]+\.html):(\d+)(?::(\d+))?\)/,
  COLUMN_INFO: /Column (\d+)/i,
  ERROR_PREFIX: /^  Error:/i,
  CALL_MATCH: /Unable to call `([^`]+)`/,
  OUTPUT_MATCH: /attempted to output '([^']+)'/i,
};
