
import { T } from '@nunjucks/nodes';
import type { Node, NodeType } from '@nunjucks/nodes';
import type { Frame } from '@nunjucks/runtime';
import type { Compiler } from './index.ts';
import {
  compileLiteral,
  compileSymbol,
  compileGroup,
  compileArray,
  compileDict,
  compileNodeList,
  compilePair,
  compileKeywordArgs,
  compileFunCall,
  compilePipeForward,
  compileLookupVal,
  compileOptionalChain,
  compileOptionalCall,
  compileSlice,
  compileCompare,
  compileIs,
  compileInlineIf,
  compileWalrus,
  compileOr,
  compileAnd,
  compileAdd,
  compileConcat,
  compileSub,
  compileMul,
  compileDiv,
  compileMod,
  compileNullishCoalesce,
  compileIn,
  compileFloorDiv,
  compilePow,
  compileNot,
  compileNeg,
  compilePos,
  compileSpread,
  compileTemplateLiteral,
  compileBitwiseOr,
  compileBitwiseAnd,
  compileBitwiseXor,
  compileBitwiseLShift,
  compileBitwiseRShift,
  compileBitwiseNot,
  compileIncrement,
  compileDecrement,
} from './expression-compiler/index.ts';

import {
  compileIf,
  compileVariableDeclaration,
  compileVariableAssignment,
  compileCompoundAssignment,
  compileDefineBlock,
  compileSwitch,
  compileFor,
  compileMacroPublic,
  compileCaller,
  compileBlock,
  compileSuper,
  compileImport,
  compileFromImport,
  compileExtends,
  compileInclude,
  compileTemplateData,
  compileCapture,
  compileOutput,
  compileRoot,
  compileCallExtension,
  compileCallExtensionAsync,
  compileDo,
  compileWith,
} from './statement-compiler/index.ts';

export type CompileFn = (ctx: Compiler, node: Node, frame: Frame) => unknown;

export const COMPILE_FUNCTIONS: Readonly<Partial<Record<NodeType, CompileFn>>> = {
  [T.NODE]: compileLiteral,
  [T.VALUE]: compileLiteral,
  [T.LITERAL]: compileLiteral,
  [T.SYMBOL]: compileSymbol,
  [T.GROUP]: compileGroup,
  [T.ARRAY]: compileArray,
  [T.DICT]: compileDict,
  [T.NODE_LIST]: compileNodeList,
  [T.PAIR]: compilePair,
  [T.INLINE_IF]: compileInlineIf,
  [T.WALRUS]: compileWalrus,
  [T.IN]: compileIn,
  [T.IS]: compileIs,
  [T.OR]: compileOr,
  [T.AND]: compileAnd,
  [T.NULLISH_COALESCE]: compileNullishCoalesce,
  [T.ADD]: compileAdd,
  [T.CONCAT]: compileConcat,
  [T.SUB]: compileSub,
  [T.MUL]: compileMul,
  [T.DIV]: compileDiv,
  [T.MOD]: compileMod,
  [T.NOT]: compileNot,
  [T.FLOOR_DIV]: compileFloorDiv,
  [T.POW]: compilePow,
  [T.NEG]: compileNeg,
  [T.POS]: compilePos,
  [T.SPREAD]: compileSpread,
  [T.TEMPLATE_LITERAL]: compileTemplateLiteral,
  [T.COMPARE]: compileCompare,
  [T.BITWISE_OR]: compileBitwiseOr,
  [T.BITWISE_AND]: compileBitwiseAnd,
  [T.BITWISE_XOR]: compileBitwiseXor,
  [T.BITWISE_LSHIFT]: compileBitwiseLShift,
  [T.BITWISE_RSHIFT]: compileBitwiseRShift,
  [T.BITWISE_NOT]: compileBitwiseNot,
  [T.INCREMENT]: compileIncrement,
  [T.DECREMENT]: compileDecrement,
  [T.LOOKUP_VAL]: compileLookupVal,
  [T.OPTIONAL_CHAIN]: compileOptionalChain,
  [T.OPTIONAL_CALL]: compileOptionalCall,
  [T.SLICE]: compileSlice,
  [T.FUN_CALL]: compileFunCall,
  [T.PIPE]: compilePipeForward,
  [T.KEYWORD_ARGS]: compileKeywordArgs,
  [T.VARIABLE_DECLARATION]: compileVariableDeclaration,
  [T.VARIABLE_ASSIGNMENT]: compileVariableAssignment,
  [T.COMPOUND_ASSIGNMENT]: compileCompoundAssignment,
  [T.DEFINE_BLOCK]: compileDefineBlock,
  [T.SWITCH]: compileSwitch,
  [T.IF]: compileIf,
  [T.FOR]: compileFor,
  [T.MACRO]: compileMacroPublic,
  [T.CALLER]: compileCaller,
  [T.IMPORT]: compileImport,
  [T.FROM_IMPORT]: compileFromImport,
  [T.BLOCK]: compileBlock,
  [T.SUPER]: compileSuper,
  [T.EXTENDS]: compileExtends,
  [T.INCLUDE]: compileInclude,
  [T.TEMPLATE_DATA]: compileTemplateData,
  [T.CAPTURE]: compileCapture,
  [T.OUTPUT]: compileOutput,
  [T.CALL_EXTENSION]: compileCallExtension,
  [T.CALL_EXTENSION_ASYNC]: compileCallExtensionAsync,
  [T.ROOT]: compileRoot,
  [T.DO]: compileDo,
  [T.WITH]: compileWith,
};

export const compileDispatch = (ctx: Compiler, node: Node, frame?: Frame): unknown => {
  const typeName = node.type;
  const fn = COMPILE_FUNCTIONS[typeName];
  if (fn) {
    return fn(ctx, node, frame as Frame);
  }

  ctx.fail(`compile: Cannot compile node: ${typeName}`, node.lineno, node.colno);
};
