import { getNodeTypeName } from '@nunjucks/nodes';
import type { Node } from '@nunjucks/nodes';
import type { Frame } from '@nunjucks/runtime';
import type { Compiler } from './index.ts';
import {
  compileLiteral,
  compileSymbol,
  compileGroup,
  compileArray,
  compileDict,
  compileNodeList,
  compilePair,
  compileKeywordArgs,
  compileFunCall,
  compilePipe,
  compilePipeAsync,
  compileLookupVal,
  compileOptionalChain,
  compileOptionalCall,
  compileSlice,
  compileCompare,
  compileIs,
  compileInlineIf,
  compileWalrus,
  compileOr,
  compileAnd,
  compileAdd,
  compileConcat,
  compileSub,
  compileMul,
  compileDiv,
  compileMod,
  compileNullishCoalesce,
  compileIn,
  compileFloorDiv,
  compilePow,
  compileNot,
  compileNeg,
  compilePos,
  compileSpread,
  compileTemplateLiteral,
  compileBitwiseOr,
  compileBitwiseAnd,
  compileBitwiseXor,
  compileBitwiseLShift,
  compileBitwiseRShift,
  compileBitwiseNot,
  compileIncrement,
  compileDecrement,
} from './expression-compiler/index.ts';

import {
  compileIf,
  compileVariableDeclaration,
  compileVariableAssignment,
  compileCompoundAssignment,
  compileDefineBlock,
  compileSwitch,
  compileFor,
  compileMacroPublic,
  compileCaller,
  compileBlock,
  compileSuper,
  compileImport,
  compileFromImport,
  compileExtends,
  compileInclude,
  compileTemplateData,
  compileCapture,
  compileOutput,
  compileRoot,
  compileCallExtension,
  compileCallExtensionAsync,
  compileDo,
  compileWith,
} from './statement-compiler/index.ts';

export type CompileFn = (ctx: Compiler, node: Node, frame: Frame) => unknown;

export const COMPILE_FUNCTIONS: Readonly<Record<string, CompileFn>> = {
  node: compileLiteral,
  value: compileLiteral,
  literal: compileLiteral,
  symbol: compileSymbol,
  group: compileGroup,
  array: compileArray,
  dict: compileDict,
  nodeList: compileNodeList,
  pair: compilePair,
  inlineIf: compileInlineIf,
  walrus: compileWalrus,
  in: compileIn,
  is: compileIs,
  or: compileOr,
  and: compileAnd,
  nullishCoalesce: compileNullishCoalesce,
  add: compileAdd,
  concat: compileConcat,
  sub: compileSub,
  mul: compileMul,
  div: compileDiv,
  mod: compileMod,
  not: compileNot,
  floorDiv: compileFloorDiv,
  pow: compilePow,
  neg: compileNeg,
  pos: compilePos,
  spread: compileSpread,
  templateLiteral: compileTemplateLiteral,
  compare: compileCompare,
  bitwiseOr: compileBitwiseOr,
  bitwiseAnd: compileBitwiseAnd,
  bitwiseXor: compileBitwiseXor,
  bitwiseLShift: compileBitwiseLShift,
  bitwiseRShift: compileBitwiseRShift,
  bitwiseNot: compileBitwiseNot,
  increment: compileIncrement,
  decrement: compileDecrement,
  lookupVal: compileLookupVal,
  optionalChain: compileOptionalChain,
  optionalCall: compileOptionalCall,
  slice: compileSlice,
  funCall: compileFunCall,
  pipe: compilePipe,
  pipeAsync: compilePipeAsync,
  keywordArgs: compileKeywordArgs,
  variableDeclaration: compileVariableDeclaration,
  variableAssignment: compileVariableAssignment,
  compoundAssignment: compileCompoundAssignment,
  defineBlock: compileDefineBlock,
  switch: compileSwitch,
  if: compileIf,
  for: compileFor,
  macro: compileMacroPublic,
  caller: compileCaller,
  import: compileImport,
  fromImport: compileFromImport,
  block: compileBlock,
  super: compileSuper,
  extends: compileExtends,
  include: compileInclude,
  templateData: compileTemplateData,
  capture: compileCapture,
  output: compileOutput,
  callExtension: compileCallExtension,
  callExtensionAsync: compileCallExtensionAsync,
  root: compileRoot,
  do: compileDo,
  with: compileWith,
};

export const compileDispatch = (ctx: Compiler, node: Node, frame?: Frame): unknown => {
  const typeName = getNodeTypeName(node);
  let fn: CompileFn | undefined;
  if (typeName === undefined) {
    fn = undefined;
  } else {
    fn = COMPILE_FUNCTIONS[typeName];
  }
  if (fn) {
    if (frame === undefined) {
      ctx.fail(`compile: Cannot compile node: ${typeName}`, node.lineno, node.colno);
    }
    return fn(ctx, node, frame);
  }

  ctx.fail(`compile: Cannot compile node: ${typeName}`, node.lineno, node.colno);
};
