// WHY: SSOT for the engine's built-in is test names — consumed by the lexer (keyword
// tokenization of x is <name> expressions) and drift-pinned against the runtime's
// BUILTIN_TESTS registry. Mirrors the BUILTIN_FILTER_NAMES pattern (ARCHITECTURE.md §6):
// the list lives in shared so neither consumer drags the other's barrel weight.
const BUILTIN_TEST_NAMES: readonly string[] = Object.freeze([
  'alpha',
  'alphanumeric',
  'array',
  'asyncfunction',
  'asynciterable',
  'between',
  'bigint',
  'blank',
  'boolean',
  'buffer',
  'contains',
  'Date',
  'defined',
  'divisibleby',
  'empty',
  'endswith',
  'equalto',
  'Error',
  'escaped',
  'even',
  'false',
  'falsy',
  'finite',
  'float',
  'function',
  'has',
  'hasown',
  'integer',
  'iterable',
  'lower',
  'Map',
  'matches',
  'nan',
  'negative',
  'none',
  'null',
  'number',
  'numeric',
  'object',
  'odd',
  'positive',
  'Promise',
  'RegExp',
  'safe',
  'sameas',
  'Set',
  'startswith',
  'string',
  'symbol',
  'true',
  'truthy',
  'typedarray',
  'undefined',
  'upper',
  'URL',
  'zero',
]);

export { BUILTIN_TEST_NAMES };
