import { describe, test, expect } from 'bun:test';
import * as mod from './index.js';

describe('error/index exports', () => {
  test('exports getConfig', () => expect(mod.getConfig).toBeFunction());
  test('exports createEnvironment', () => expect(mod.createEnvironment).toBeFunction());
  test('exports getEnvironment', () => expect(mod.getEnvironment).toBeFunction());
  test('exports renderError', () => expect(mod.renderError).toBeFunction());
  test('exports renderErrorString', () => expect(mod.renderErrorString).toBeFunction());
  test('exports createErrorFormatter', () => expect(mod.createErrorFormatter).toBeFunction());
  test('exports TemplateError', () => expect(mod.TemplateError).toBeFunction());
  test('exports createTemplateError', () => expect(mod.createTemplateError).toBeFunction());
  test('exports prettifyError', () => expect(mod.prettifyError).toBeFunction());
  test('exports classifyError', () => expect(mod.classifyError).toBeFunction());
  test('exports resolveIdeLink', () => expect(mod.resolveIdeLink).toBeFunction());
  test('exports getIdeMeta', () => expect(mod.getIdeMeta).toBeFunction());
  test('exports extractUndefinedName', () => expect(mod.extractUndefinedName).toBeFunction());
  test('exports extractLineInfo', () => expect(mod.extractLineInfo).toBeFunction());
  test('exports extractColFromMessage', () => expect(mod.extractColFromMessage).toBeFunction());
  test('exports extractIncludeChainFromMessage', () => expect(mod.extractIncludeChainFromMessage).toBeFunction());
  test('exports extractErrorTemplateName', () => expect(mod.extractErrorTemplateName).toBeFunction());
  test('exports normalizeLine', () => expect(mod.normalizeLine).toBeFunction());
  test('exports normalizeCol', () => expect(mod.normalizeCol).toBeFunction());
  test('exports getDisplayLine', () => expect(mod.getDisplayLine).toBeFunction());
  test('exports getDisplayCol', () => expect(mod.getDisplayCol).toBeFunction());
  test('exports getFallbackLine', () => expect(mod.getFallbackLine).toBeFunction());
  test('exports getFallbackCol', () => expect(mod.getFallbackCol).toBeFunction());
  test('exports mergeLine', () => expect(mod.mergeLine).toBeFunction());
  test('exports mergeCol', () => expect(mod.mergeCol).toBeFunction());
  test('exports createDisplayLine', () => expect(mod.createDisplayLine).toBeFunction());
  test('exports createDisplayCol', () => expect(mod.createDisplayCol).toBeFunction());
  test('exports getSnippet', () => expect(mod.getSnippet).toBeFunction());
  test('exports extractLineFromSnippet', () => expect(mod.extractLineFromSnippet).toBeFunction());
  test('exports splitSnippetLines', () => expect(mod.splitSnippetLines).toBeFunction());
  test('exports createErrorData', () => expect(mod.createErrorData).toBeFunction());
  test('exports formatLocation', () => expect(mod.formatLocation).toBeFunction());
  test('exports getDisplayMessage', () => expect(mod.getDisplayMessage).toBeFunction());
  test('exports formatCodeTrace', () => expect(mod.formatCodeTrace).toBeFunction());
  test('exports toConsoleString', () => expect(mod.toConsoleString).toBeFunction());
  test('exports toHtmlString', () => expect(mod.toHtmlString).toBeFunction());
  test('exports CSS', () => expect(mod.CSS).toBeString());
  test('exports PRODUCTION_BODY', () => expect(mod.PRODUCTION_BODY).toBeString());
  test('exports TOGGLE_SCRIPT', () => expect(mod.TOGGLE_SCRIPT).toBeString());
});
